backend:
  name: github
  site_domain: iridescent-liger-42344e.netlify.app
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم المنتج", name: "title", widget: "string" }
      - { label: "السعر", name: "price", widget: "string" }
      - { label: "الصورة", name: "image", widget: "image" }
      - { label: "الوصف", name: "body", widget: "markdown" }
